solrMaven/lib/jsf-1_1_01/jsf-1_1_01/samples/cardemo/src/java/carstore/CustomerBean.java
/*
 * $Id: CustomerBean.java,v 1.1 2004/05/20 17:07:22 jvisvanathan Exp $
 */
/*
 * Copyright 2004 Sun Microsystems, Inc. All Rights Reserved.
 * 
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 * 
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 * 
 * - Redistribution in binary form must reproduce the above
 *   copyright notice, this list of conditions and the following
 *   disclaimer in the documentation and/or other materials
 *   provided with the distribution.
 *    
 * Neither the name of Sun Microsystems, Inc. or the names of
 * contributors may be used to endorse or promote products derived
 * from this software without specific prior written permission.
 *  
 * This software is provided "AS IS," without a warranty of any
 * kind. ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND
 * WARRANTIES, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE HEREBY
 * EXCLUDED. SUN AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY
 * DAMAGES OR LIABILITIES SUFFERED BY LICENSEE AS A RESULT OF OR
 * RELATING TO USE, MODIFICATION OR DISTRIBUTION OF THIS SOFTWARE OR
 * ITS DERIVATIVES. IN NO EVENT WILL SUN OR ITS LICENSORS BE LIABLE
 * FOR ANY LOST REVENUE, PROFIT OR DATA, OR FOR DIRECT, INDIRECT,
 * SPECIAL, CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER
 * CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY, ARISING OUT OF
 * THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF SUN HAS
 * BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 *  
 * You acknowledge that this software is not designed, licensed or
 * intended for use in the design, construction, operation or
 * maintenance of any nuclear facility.
 */

package carstore;

import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;

import java.util.ArrayList;
import java.util.Collection;
import java.util.ResourceBundle;

public class CustomerBean extends Object {


    String firstName = null;
    String middleInitial = null;
    String lastName = null;
    String mailingAddress = null;
    String city = null;
    String state = null;
    String zip = null;
    String month = null;
    String year = null;


    public CustomerBean() {
        super();
    }


    protected Collection titleOptions = null;


    public Collection getTitleOptions() {
        titleOptions = new ArrayList();
        ResourceBundle rb = ResourceBundle.getBundle(
            "carstore.bundles.Resources",
            (FacesContext.getCurrentInstance().getViewRoot().getLocale()));
        String titleStr = (String) rb.getObject("mrLabel");
        titleOptions.add(new SelectItem(titleStr, titleStr,
                                        titleStr));
        titleStr = (String) rb.getObject("mrsLabel");
        titleOptions.add(new SelectItem(titleStr, titleStr,
                                        titleStr));
        titleStr = (String) rb.getObject("msLabel");
        titleOptions.add(new SelectItem(titleStr, titleStr,
                                        titleStr));

        return titleOptions;
    }


    public void setTitleOptions(Collection newOptions) {
        titleOptions = new ArrayList(newOptions);
    }


    String title = null;


    public void setCurrentTitle(String newTitle) {
        title = newTitle;
    }


    public String getCurrentTitle() {
        return title;
    }


    public void setFirstName(String first) {
        firstName = first;
    }


    public String getFirstName() {
        return firstName;
    }


    public void setMiddleInitial(String mI) {
        middleInitial = mI;
    }


    public String getMiddleInitial() {
        return middleInitial;
    }


    public void setLastName(String last) {
        lastName = last;
    }


    public String getLastName() {
        return lastName;
    }


    public void setMailingAddress(String mA) {
        mailingAddress = mA;
    }


    public String getMailingAddress() {
        return mailingAddress;
    }


    public void setCity(String cty) {
        city = cty;
    }


    public String getCity() {
        return city;
    }


    public void setState(String sT) {
        state = sT;
    }


    public String getState() {
        return state;
    }


    public void setZip(String zipCode) {
        zip = zipCode;
    }


    public String getZip() {
        return zip;
    }


    public void setMonth(String mth) {
        month = mth;
    }


    public String getMonth() {
        return month;
    }


    public void setYear(String yr) {
        year = yr;
    }


    public String getYear() {
        return year;
    }
}

solrMaven/lib/jsf-1_1_01/jsf-1_1_01/samples/cardemo/web/bottomMatter.jsp
<!--
 Copyright 2004 Sun Microsystems, Inc. All Rights Reserved.
 
 Redistribution and use in source and binary forms, with or
 without modification, are permitted provided that the following
 conditions are met:
 
 - Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 
 - Redistribution in binary form must reproduce the above
   copyright notice, this list of conditions and the following
   disclaimer in the documentation and/or other materials
   provided with the distribution.
    
 Neither the name of Sun Microsystems, Inc. or the names of
 contributors may be used to endorse or promote products derived
 from this software without specific prior written permission.
  
 This software is provided "AS IS," without a warranty of any
 kind. ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND
 WARRANTIES, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE HEREBY
 EXCLUDED. SUN AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY
 DAMAGES OR LIABILITIES SUFFERED BY LICENSEE AS A RESULT OF OR
 RELATING TO USE, MODIFICATION OR DISTRIBUTION OF THIS SOFTWARE OR
 ITS DERIVATIVES. IN NO EVENT WILL SUN OR ITS LICENSORS BE LIABLE
 FOR ANY LOST REVENUE, PROFIT OR DATA, OR FOR DIRECT, INDIRECT,
 SPECIAL, CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER
 CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY, ARISING OUT OF
 THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF SUN HAS
 BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
  
 You acknowledge that this software is not designed, licensed or
 intended for use in the design, construction, operation or
 maintenance of any nuclear facility.
-->
<%@ page contentType="text/html" language="java" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<f:subview id="bottom">

  <h:outputLink value="javadocs">
     <f:verbatim>Documentation for this demo</f:verbatim>
  </h:outputLink>

</f:subview>

solrMaven/lib/jsf-1_1_01/jsf-1_1_01/samples/cardemo/web/carDetail.jsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">

<!--
 Copyright 2004 Sun Microsystems, Inc. All Rights Reserved.
 
 Redistribution and use in source and binary forms, with or
 without modification, are permitted provided that the following
 conditions are met:
 
 - Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 
 - Redistribution in binary form must reproduce the above
   copyright notice, this list of conditions and the following
   disclaimer in the documentation and/or other materials
   provided with the distribution.
    
 Neither the name of Sun Microsystems, Inc. or the names of
 contributors may be used to endorse or promote products derived
 from this software without specific prior written permission.
  
 This software is provided "AS IS," without a warranty of any
 kind. ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND
 WARRANTIES, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE HEREBY
 EXCLUDED. SUN AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY
 DAMAGES OR LIABILITIES SUFFERED BY LICENSEE AS A RESULT OF OR
 RELATING TO USE, MODIFICATION OR DISTRIBUTION OF THIS SOFTWARE OR
 ITS DERIVATIVES. IN NO EVENT WILL SUN OR ITS LICENSORS BE LIABLE
 FOR ANY LOST REVENUE, PROFIT OR DATA, OR FOR DIRECT, INDIRECT,
 SPECIAL, CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER
 CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY, ARISING OUT OF
 THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF SUN HAS
 BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
  
 You acknowledge that this software is not designed, licensed or
 intended for use in the design, construction, operation or
 maintenance of any nuclear facility.
-->

<HTML>

<HEAD>
	<META HTTP-EQUIV="Content-Type" CONTENT="text/html;CHARSET=iso-8859-1">
	<TITLE>CarStore</TITLE>
        <link rel="stylesheet" type="text/css"
            href='<%= request.getContextPath() + "/stylesheet.css" %>'>
</HEAD>

<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>

     <f:loadBundle basename="carstore.bundles.Resources" var="bundle"/>

<BODY BGCOLOR="white">

<f:view>

    <h:form>


        <!-- non-option details -->

        <h:panelGrid columns="1"
                      summary="#{bundle.carDetails}"
                      title="#{bundle.carDetails}">

            <h:graphicImage  url="/images/cardemo.jpg" /> 

            <h:graphicImage 
               binding="#{carstore.currentModel.components.image}" />

            <h:outputText styleClass="subtitlebig"
               binding="#{carstore.currentModel.components.title}" />
            
            <h:outputText 
               binding="#{carstore.currentModel.components.description}" />

            <h:panelGrid columns="2">

	      <h:outputText styleClass="subtitle"
                             value="#{bundle.basePriceLabel}" />

	      <h:outputText 
		 binding="#{carstore.currentModel.components.basePrice}" />

	      <h:outputText styleClass="subtitle"
                             value="#{bundle.yourPriceLabel}" />

	      <h:outputText value="#{carstore.currentModel.currentPrice}" />

            </h:panelGrid>

            <h:commandButton action="#{carstore.buyCurrentCar}"
                 value="#{bundle.buy}" />

        </h:panelGrid>

        <jsp:include page="optionsPanel.jsp"/>

        <h:commandButton value="#{bundle.recalculate}" 
                      action="#{carstore.currentModel.updatePricing}" />

        <h:commandButton action="#{carstore.buyCurrentCar}"
                 value="#{bundle.buy}" />

</h:form>

 <jsp:include page="bottomMatter.jsp"/>

</f:view>
</BODY>

</HTML>

solrMaven/lib/jsf-1_1_01/jsf-1_1_01/samples/cardemo/web/confirmChoices.jsp
<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<!--
 Copyright 2004 Sun Microsystems, Inc. All Rights Reserved.
 
 Redistribution and use in source and binary forms, with or
 without modification, are permitted provided that the following
 conditions are met:
 
 - Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 
 - Redistribution in binary form must reproduce the above
   copyright notice, this list of conditions and the following
   disclaimer in the documentation and/or other materials
   provided with the distribution.
    
 Neither the name of Sun Microsystems, Inc. or the names of
 contributors may be used to endorse or promote products derived
 from this software without specific prior written permission.
  
 This software is provided "AS IS," without a warranty of any
 kind. ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND
 WARRANTIES, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE HEREBY
 EXCLUDED. SUN AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY
 DAMAGES OR LIABILITIES SUFFERED BY LICENSEE AS A RESULT OF OR
 RELATING TO USE, MODIFICATION OR DISTRIBUTION OF THIS SOFTWARE OR
 ITS DERIVATIVES. IN NO EVENT WILL SUN OR ITS LICENSORS BE LIABLE
 FOR ANY LOST REVENUE, PROFIT OR DATA, OR FOR DIRECT, INDIRECT,
 SPECIAL, CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER
 CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY, ARISING OUT OF
 THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF SUN HAS
 BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
  
 You acknowledge that this software is not designed, licensed or
 intended for use in the design, construction, operation or
 maintenance of any nuclear facility.
-->

<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>

<HTML>

<HEAD>
	<TITLE>Welcome to CarStore</TITLE>
        <link rel="stylesheet" type="text/css"
            href='<%= request.getContextPath() + "/stylesheet.css" %>'>
</HEAD>

<BODY BGCOLOR="white">

<f:loadBundle basename="carstore.bundles.Resources" var="bundle"/>
<f:view>  
<h:form>
 
<h:panelGrid id="mainPanel" columns="1" footerClass="subtitle"
   styleClass="medium" columnClasses="medium">

  <h:graphicImage  url="/images/cardemo.jpg" />
  <h:outputText binding="#{carstore.currentModel.components.title}" />
    
<h:panelGrid columns="2"  footerClass="subtitle"
   headerClass="subtitlebig" styleClass="medium" columnClasses="subtitle,medium">
    
    <f:facet name="header">
      <h:outputText  value="#{bundle.buyTitle}" />
    </f:facet>

    <h:outputText value="#{bundle.Engine}" />

    <h:outputText value="#{carstore.currentModel.attributes.engine}"  />

    <h:outputText value="#{bundle.Brakes}" />

    <h:outputText  value="#{carstore.currentModel.attributes.brake}" />

    <h:outputText  value="#{bundle.Suspension}" />

    <h:outputText  value="#{carstore.currentModel.attributes.suspension}" />

    <h:outputText  value="#{bundle.Speakers}" />

    <h:outputText  value="#{carstore.currentModel.attributes.speaker}" />

    <h:outputText  value="#{bundle.Audio}" />

    <h:outputText  value="#{carstore.currentModel.attributes.audio}" />

    <h:outputText  value="#{bundle.Transmission}" />

    <h:outputText  value="#{carstore.currentModel.attributes.transmission}" />

    <h:outputText  value="#{bundle.sunroofLabel}"  />

    <h:outputText  value="#{carstore.currentModel.attributes.sunroof}" />

    <h:outputText  value="#{bundle.cruiseLabel}"  />

    <h:outputText  value="#{carstore.currentModel.attributes.cruisecontrol}" />

    <h:outputText value="#{bundle.keylessLabel}"  />

    <h:outputText  value="#{carstore.currentModel.attributes.keylessentry}" />

    <h:outputText  value="#{bundle.securityLabel}"  />

    <h:outputText  value="#{carstore.currentModel.attributes.securitySystem}" />

    <h:outputText  value="#{bundle.skiRackLabel}"  />

    <h:outputText  value="#{carstore.currentModel.attributes.skiRack}" />

    <h:outputText  value="#{bundle.towPkgLabel}"  />

    <h:outputText  value="#{carstore.currentModel.attributes.towPackage}" />

    <h:outputText  value="#{bundle.gpsLabel}"  />

    <h:outputText  value="#{carstore.currentModel.attributes.gps}" />
    
  <f:facet name="footer">
     <h:panelGroup>
        <h:outputText  value="#{bundle.yourPriceLabel}"  />
        &nbsp;
        <h:outputText  value="#{carstore.currentModel.currentPrice}" />
     </h:panelGroup>
  </f:facet>

</h:panelGrid>

<h:panelGroup>
<h:commandButton value="#{bundle.buy}" action="customerInfo" title="#{bundle.buy}" />
<h:commandButton value="#{bundle.back}" action="carDetail" title="#{bundle.back}"/>
</h:panelGroup>

</h:panelGrid>
</h:form>
<jsp:include page="bottomMatter.jsp"/>
</f:view>

</BODY>
</HTML>

solrMaven/lib/jsf-1_1_01/jsf-1_1_01/samples/cardemo/web/customerInfo.jsp
<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<!--
 Copyright 2004 Sun Microsystems, Inc. All Rights Reserved.
 
 Redistribution and use in source and binary forms, with or
 without modification, are permitted provided that the following
 conditions are met:
 
 - Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 
 - Redistribution in binary form must reproduce the above
   copyright notice, this list of conditions and the following
   disclaimer in the documentation and/or other materials
   provided with the distribution.
    
 Neither the name of Sun Microsystems, Inc. or the names of
 contributors may be used to endorse or promote products derived
 from this software without specific prior written permission.
  
 This software is provided "AS IS," without a warranty of any
 kind. ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND
 WARRANTIES, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE HEREBY
 EXCLUDED. SUN AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY
 DAMAGES OR LIABILITIES SUFFERED BY LICENSEE AS A RESULT OF OR
 RELATING TO USE, MODIFICATION OR DISTRIBUTION OF THIS SOFTWARE OR
 ITS DERIVATIVES. IN NO EVENT WILL SUN OR ITS LICENSORS BE LIABLE
 FOR ANY LOST REVENUE, PROFIT OR DATA, OR FOR DIRECT, INDIRECT,
 SPECIAL, CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER
 CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY, ARISING OUT OF
 THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF SUN HAS
 BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
  
 You acknowledge that this software is not designed, licensed or
 intended for use in the design, construction, operation or
 maintenance of any nuclear facility.
-->

<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
   <title>Customer Details</title>
   <link rel="stylesheet" type="text/css"
            href='<%= request.getContextPath() + "/stylesheet.css" %>'>
    
    <%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
    <%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
    <%@ taglib uri="/WEB-INF/carstore.tld" prefix="cs" %>
</head>
<body>

<f:loadBundle basename="carstore.bundles.Resources" var="bundle"/>

<f:view>
<h:form >

<h:panelGrid id="mainPanel" columns="1" footerClass="subtitle"
   headerClass="subtitlebig" styleClass="medium" columnClasses="medium">

  <h:graphicImage  url="/images/cardemo.jpg" />

  <h:outputText value="#{bundle.customerTitle}" />

  <h:panelGrid id="subPanel" columns="3" footerClass="medium"
     headerClass="subtitlebig" styleClass="medium" columnClasses="medium">

    <h:outputText value="#{bundle.titleLabel}" />
    <h:selectOneMenu id="title" value="#{customer.currentTitle}">
        <f:selectItems value="#{customer.titleOptions}" />
    </h:selectOneMenu>
    <h:outputText value=""/>

    <h:outputText value="#{bundle.firstLabel}" />
    <h:inputText  id="firstName" value="#{customer.firstName}" required="true"> 
        <f:valueChangeListener type="carstore.FirstNameChanged" />
    </h:inputText>
    <h:message styleClass="validationMessage"  for="firstName"/>

    <h:outputText value="#{bundle.middleLabel}" />
    <h:inputText id="middleInitial" size="1" maxlength="1" 
            value="#{customer.middleInitial}" > 
        </h:inputText>
    <h:message  styleClass="validationMessage" for="middleInitial"/>

    <h:outputText value="#{bundle.lastLabel}" />
    <h:inputText  value="#{customer.lastName}" />
    <h:outputText value=""/>

    <h:outputText value="#{bundle.mailingLabel}"/>
    <h:inputText  value="#{customer.mailingAddress}" />
    <h:outputText value=""/>

    <h:outputText value="#{bundle.cityLabel}" />
    <h:inputText  value="#{customer.city}" />
    <h:outputText value=""/>

    <h:outputText value="#{bundle.stateLabel}" />
    <h:selectOneMenu  value="#{customer.state}" >

		<f:selectItem  itemValue="AL" itemLabel="AL" />
		<f:selectItem  itemValue="AK" itemLabel="AK"/>
		<f:selectItem  itemValue="AZ" itemLabel="AZ"/>
		<f:selectItem  itemValue="AR" itemLabel="AR"/>
		<f:selectItem  itemValue="CA" itemLabel="CA"/>
		<f:selectItem  itemValue="CO" itemLabel="CO"/>
		<f:selectItem  itemValue="CT" itemLabel="CT"/>
		<f:selectItem  itemValue="DE" itemLabel="DE"/>
		<f:selectItem  itemValue="FL" itemLabel="FL"/>
		<f:selectItem  itemValue="GA" itemLabel="GA"/>

		<f:selectItem  itemValue="HI" itemLabel="HI"/>
		<f:selectItem  itemValue="ID" itemLabel="ID"/>
		<f:selectItem  itemValue="IL" itemLabel="IL"/>
		<f:selectItem  itemValue="IN" itemLabel="IN"/>
		<f:selectItem  itemValue="IA" itemLabel="IA"/>
		<f:selectItem  itemValue="KS" itemLabel="KS"/>
		<f:selectItem  itemValue="KY" itemLabel="KY"/>
		<f:selectItem  itemValue="LA" itemLabel="LA"/>
		<f:selectItem  itemValue="ME" itemLabel="ME"/>
		<f:selectItem  itemValue="MD" itemLabel="MD"/>

		<f:selectItem  itemValue="MA" itemLabel="MA"/>
		<f:selectItem  itemValue="MI" itemLabel="MI"/>
		<f:selectItem  itemValue="MN" itemLabel="MN"/>
		<f:selectItem  itemValue="MO" itemLabel="MO"/>
		<f:selectItem  itemValue="MT" itemLabel="MT"/>
		<f:selectItem  itemValue="NE" itemLabel="NE"/>
		<f:selectItem  itemValue="NV" itemLabel="NV"/>
		<f:selectItem  itemValue="NH" itemLabel="NH"/>
		<f:selectItem  itemValue="NJ" itemLabel="NJ"/>
		<f:selectItem  itemValue="NM" itemLabel="NM"/>

		<f:selectItem  itemValue="MY" itemLabel="MY"/>
		<f:selectItem  itemValue="NC" itemLabel="NC"/>
		<f:selectItem  itemValue="ND" itemLabel="ND"/>
		<f:selectItem  itemValue="OH" itemLabel="OH"/>
		<f:selectItem  itemValue="OK" itemLabel="OK"/>
		<f:selectItem  itemValue="OR" itemLabel="OR"/>
		<f:selectItem  itemValue="PA" itemLabel="PA"/>
		<f:selectItem  itemValue="RI" itemLabel="RI"/>
		<f:selectItem  itemValue="SC" itemLabel="SC"/>
		<f:selectItem  itemValue="SD" itemLabel="SD"/>

		<f:selectItem  itemValue="TN" itemLabel="TN"/>
		<f:selectItem  itemValue="TX" itemLabel="TX"/>
		<f:selectItem  itemValue="UT" itemLabel="UT"/>
		<f:selectItem  itemValue="VT" itemLabel="VT"/>
		<f:selectItem  itemValue="VA" itemLabel="VA"/>
		<f:selectItem  itemValue="WA" itemLabel="WA"/>
		<f:selectItem  itemValue="WV" itemLabel="WV"/>
		<f:selectItem  itemValue="WI" itemLabel="WI"/>
		<f:selectItem  itemValue="WY" itemLabel="WY"/>
    </h:selectOneMenu>
    <h:outputText value=""/>

    <h:outputText  value="#{bundle.zipLabel}" />
    <h:inputText id="zip"  
			value="#{customer.zip}"
                        size="10" required="true">
          <cs:format_validator formatPatterns="99999|99999-9999|### ###"/> 
    </h:inputText>
    <h:message  styleClass="validationMessage" for="zip" />

    <h:outputText  value="#{bundle.ccNumberLabel}" />
    <h:inputText id="ccno" size="16"
           converter="creditCardConverter" required="true">
          <cs:format_validator 
          formatPatterns="9999999999999999|9999 9999 9999 9999|9999-9999-9999-9999"/>
     </h:inputText>
     <h:message styleClass="validationMessage"  for="ccno"/>  
 
    <h:outputText  value="#{bundle.monthLabel}" />
    <h:panelGrid id="monthYearPanel" columns="2" footerClass="medium"
            headerClass="medium" styleClass="medium" columnClasses="medium">
      <h:selectOneMenu  value="#{customer.month}">
        <f:selectItem itemValue="01" itemLabel="01"/>
        <f:selectItem itemValue="02" itemLabel="02"/>
        <f:selectItem itemValue="03" itemLabel="03"/>
        <f:selectItem itemValue="04" itemLabel="04"/>
        <f:selectItem itemValue="05" itemLabel="05"/>
        <f:selectItem itemValue="06" itemLabel="06"/>
        <f:selectItem itemValue="07" itemLabel="07"/>
        <f:selectItem itemValue="08" itemLabel="08"/>
        <f:selectItem itemValue="09" itemLabel="09"/>
        <f:selectItem itemValue="10" itemLabel="10"/>
        <f:selectItem itemValue="11" itemLabel="11"/>
        <f:selectItem itemValue="12" itemLabel="12"/>
    </h:selectOneMenu>

      <h:selectOneMenu  value="#{customer.year}" >
        <f:selectItem itemValue="2002" itemLabel="2002"/>
        <f:selectItem itemValue="2003" itemLabel="2003"/>
        <f:selectItem itemValue="2004" itemLabel="2004"/>
        <f:selectItem itemValue="2005" itemLabel="2005"/>
        <f:selectItem itemValue="2006" itemLabel="2006"/>
        <f:selectItem itemValue="2007" itemLabel="2007"/>
        <f:selectItem itemValue="2008" itemLabel="2008"/>
    </h:selectOneMenu>
    </h:panelGrid>
    <h:outputText value=""/>

 </h:panelGrid>

<h:commandButton  value="#{bundle.finishButton}" action="finish" />

<h:graphicImage id="duke" url="/images/duke.gif" />

<h:outputText  value="#{bundle.buyLabel}" />

</h:panelGrid>

</h:form>
</f:view>
</body>
</html>